#!/bin/bash
# go to the root of the package
cd "$(dirname -- "${BASH_SOURCE[0]}")/.."

echo "Create challenge1_waypoints_01"
scripts/generate_data_from_world \
  'worlds/farm_vineyard_crops_challenge1.world' 'data/challenge1_waypoints_01'
