#!/usr/bin/env python3
import sys
from pymap3d import enu
import json
import xml.etree.ElementTree as ET


MODEL_KEYWORD = 'Construction Cone'


def extract_anchor(root: ET.Element):
    coords = root.find('./world/spherical_coordinates')
    anchor = (
        float(coords.findtext('latitude_deg')),
        float(coords.findtext('longitude_deg')),
        float(coords.findtext('elevation')),
    )
    return anchor


def extract_models_pos(root: ET.Element, anchor, prefix):
    data = []
    models = root.findall('./world/state/model')

    for model in models:
        if model.attrib['name'].startswith(prefix):
            str_values = model.findtext('pose').split(' ')[0:3]
            pos = tuple(map(float, str_values))
            coords = enu.enu2geodetic(*pos, *anchor)
            data.append(list(coords) + list(pos))
            
    return data


def save_csv(data, filename):
    file = open(filename, 'w')
    file.write('latitude,longitude,altitude,x,y,z\n')

    waypoints = [data['start'], data['end']] + data['waypoints']

    for pt in waypoints:
        file.write(','.join(map(str, pt)) + '\n')

    file.close()


def save_geojson(data, filename):
    waypoints = [data['start'], data['end']] + data['waypoints']

    features = []
    for point in waypoints:
        features.append({
            "type": "Feature",
            "properties": {},
            "geometry": {
                "coordinates": [point[1], point[0]],
                "type": "Point"
            }
        })

    root = {
        "type": "FeatureCollection",
        "features": features,
    }

    with open(filename, 'w') as file:
        json.dump(root, file, indent=2)


def save_json(data, filename):
    with open(filename, 'w') as file:
        json.dump(data, file, indent=2)


def generate_data(world_filename):
    root = ET.parse(world_filename).getroot()

    anchor = extract_anchor(root)
    waypoints = extract_models_pos(root, anchor, MODEL_KEYWORD)

    data = {
        'origin': anchor,
        'start': waypoints[0],
        'end': waypoints[1],
        'waypoints': waypoints[2:],
        'fields': {
            'vineyard': {},
            'crops_field': {}
        },
    }
    return data


if __name__ == '__main__':
    if len(sys.argv) < 3:
        print(f"Syntax: {sys.argv[0]} <world_file> <output_file_base>", file=sys.stderr)
        exit(1)

    world_filename = sys.argv[1]
    output_name = sys.argv[2]

    data = generate_data(world_filename)
    save_csv(data, output_name + '.csv')
    save_geojson(data, output_name + '.geojson')
    save_json(data, output_name + '.json')
